[[DecFP]]
arch = "aarch64"
git-tree-sha1 = "4d867ed7e67a9b67ccb455fa54efab991828562d"
os = "macos"

    [[DecFP.download]]
    sha256 = "7fb3ac34656b0df200c4f6483ca09fbf5e163d46c1debcc6e617758be97f00ec"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.300+0/DecFP.v2.0.300.aarch64-apple-darwin.tar.gz"
[[DecFP]]
arch = "aarch64"
git-tree-sha1 = "0ec5f16056d1fa7675201bff9fd824a68c6e5fdb"
libc = "glibc"
os = "linux"

    [[DecFP.download]]
    sha256 = "5aa9587c760cd918b3c08c92fb1db72550b6cde1e71ed23fbc8552af1432fc2c"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.300+0/DecFP.v2.0.300.aarch64-linux-gnu.tar.gz"
[[DecFP]]
arch = "aarch64"
git-tree-sha1 = "498cf37569ec1479490052e9af22036ed5822ff8"
libc = "musl"
os = "linux"

    [[DecFP.download]]
    sha256 = "180dec551942b4f01d46664e5c5be552ce89594fa7ae081533321f44f64a7f0a"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.300+0/DecFP.v2.0.300.aarch64-linux-musl.tar.gz"
[[DecFP]]
arch = "aarch64"
git-tree-sha1 = "d48aff7d91b83984c82cabf5c5662bea22d76aab"
os = "freebsd"

    [[DecFP.download]]
    sha256 = "22607b21668413648959dd9860e83e7c8cfcda58a4cd60a63429a58bd98ea012"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.300+0/DecFP.v2.0.300.aarch64-unknown-freebsd.tar.gz"
[[DecFP]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c1731b829d2b2aaae57ed561449d782f6c3b75ce"
libc = "glibc"
os = "linux"

    [[DecFP.download]]
    sha256 = "231e123f2c4016993abf8b6e11c27308615b6e22e1c780a45d061d39485a2dee"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.300+0/DecFP.v2.0.300.armv6l-linux-gnueabihf.tar.gz"
[[DecFP]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "781a323831c31b338dc3b9c04602eb3c96165c2f"
libc = "musl"
os = "linux"

    [[DecFP.download]]
    sha256 = "71e9a4d4f7512b5f698566079554a7c25d361d903f2b24e347d642c1ace627da"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.300+0/DecFP.v2.0.300.armv6l-linux-musleabihf.tar.gz"
[[DecFP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "507f960f369fa96856c4221f888d9e039d964b3a"
libc = "glibc"
os = "linux"

    [[DecFP.download]]
    sha256 = "1f1cdea4208bc03cafecbe5fb6e8b20d32e0a0e986c235b51836d16d5cf7014b"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.300+0/DecFP.v2.0.300.armv7l-linux-gnueabihf.tar.gz"
[[DecFP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "38c9bb99c9c52102e4fc68e3443c945ec561d627"
libc = "musl"
os = "linux"

    [[DecFP.download]]
    sha256 = "1ffa47670c7452f0cb73b8684c2c3f798f35b0b852cd6ac25f21c470f14442e2"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.300+0/DecFP.v2.0.300.armv7l-linux-musleabihf.tar.gz"
[[DecFP]]
arch = "i686"
git-tree-sha1 = "159aac1af0f25c2bd2eb6d1ed8e8e6ee60f81771"
libc = "glibc"
os = "linux"

    [[DecFP.download]]
    sha256 = "0218af238fc1c2f65a2ce9eb60609c52a1eeeaa80cf235eea014fb3fb8b1690d"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.300+0/DecFP.v2.0.300.i686-linux-gnu.tar.gz"
[[DecFP]]
arch = "i686"
git-tree-sha1 = "bcf9e124bf9d50755bd99e67ff2beb70153c3b09"
libc = "musl"
os = "linux"

    [[DecFP.download]]
    sha256 = "979b7859f6e26c694e479414f9098b88f37021e79531679b9589f85428f95b4b"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.300+0/DecFP.v2.0.300.i686-linux-musl.tar.gz"
[[DecFP]]
arch = "i686"
git-tree-sha1 = "6a95392410451fb6d212579c3c938abedad31b27"
os = "windows"

    [[DecFP.download]]
    sha256 = "01a8bcc44750ab595182cde0d5e940c648dcb12d5ec33136f11d5b45b210b5a7"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.300+0/DecFP.v2.0.300.i686-w64-mingw32.tar.gz"
[[DecFP]]
arch = "powerpc64le"
git-tree-sha1 = "d23afcce640aae0efb947f1112623440d2bb8d78"
libc = "glibc"
os = "linux"

    [[DecFP.download]]
    sha256 = "e73abb282aa35416b31492a3aa272257938dfa03bb132a4aab1337b99517a994"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.300+0/DecFP.v2.0.300.powerpc64le-linux-gnu.tar.gz"
[[DecFP]]
arch = "riscv64"
git-tree-sha1 = "e3a9badd6e8a5ef30b043e2d2258c5688ac0b211"
libc = "glibc"
os = "linux"

    [[DecFP.download]]
    sha256 = "6cd8fdc6cfb3b968fcae015469b53ae370394cd5c39df3802acdcf8c83535589"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.300+0/DecFP.v2.0.300.riscv64-linux-gnu.tar.gz"
[[DecFP]]
arch = "x86_64"
git-tree-sha1 = "2e6cecc3d9e8a7d0299e6a3403932c137c815380"
os = "macos"

    [[DecFP.download]]
    sha256 = "4805a83c8a7f1ab9a3f8e861948fb14aa337869f7438f9106a8e2934a89e480e"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.300+0/DecFP.v2.0.300.x86_64-apple-darwin.tar.gz"
[[DecFP]]
arch = "x86_64"
git-tree-sha1 = "e99fa3806bf4b2048a67c4087d90b7857213b09e"
libc = "glibc"
os = "linux"

    [[DecFP.download]]
    sha256 = "8583dadbe995f0c48bf64b8ceb8c20c2a2a921fb592c5013d1fbb60928277165"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.300+0/DecFP.v2.0.300.x86_64-linux-gnu.tar.gz"
[[DecFP]]
arch = "x86_64"
git-tree-sha1 = "040dbd19d0fd5c3f0a140ab4f0bfb2a4cf6a5855"
libc = "musl"
os = "linux"

    [[DecFP.download]]
    sha256 = "ec67bf9a1a71a626690737893ab9d755b02ca71401004e190a4a603becc547aa"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.300+0/DecFP.v2.0.300.x86_64-linux-musl.tar.gz"
[[DecFP]]
arch = "x86_64"
git-tree-sha1 = "430cc20d1d1c8cd2720eff2bf46968281fdf2c4e"
os = "freebsd"

    [[DecFP.download]]
    sha256 = "cc67817861f34e463104e3c4fc304c708d5debc769614a372a0f94accb7fe761"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.300+0/DecFP.v2.0.300.x86_64-unknown-freebsd.tar.gz"
[[DecFP]]
arch = "x86_64"
git-tree-sha1 = "d7c7d14d7fd96e7124c21f61cba143f7a4921076"
os = "windows"

    [[DecFP.download]]
    sha256 = "3c7981dbb287e46d5fd2ef25c416463b95ee0d77d9b2c1af89d96fac104f1abe"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.300+0/DecFP.v2.0.300.x86_64-w64-mingw32.tar.gz"
