[[DecFP]]
arch = "aarch64"
git-tree-sha1 = "7ea592bb4ceaa5da532ac96aff056eef0441f325"
os = "macos"

    [[DecFP.download]]
    sha256 = "e4366e45c0d1df578ece01db2172980bf105ca6926985feb74d438cfec9a3bb3"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.3+0/DecFP.v2.0.3.aarch64-apple-darwin.tar.gz"
[[DecFP]]
arch = "aarch64"
git-tree-sha1 = "f40f1b9ebab917548e775cf79c0909a57651c75b"
libc = "glibc"
os = "linux"

    [[DecFP.download]]
    sha256 = "56f1ac4b4f973a0d508dbe458450a68eb039d02845310d6f3c326e1fcd15b066"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.3+0/DecFP.v2.0.3.aarch64-linux-gnu.tar.gz"
[[DecFP]]
arch = "aarch64"
git-tree-sha1 = "a62b59ec56045656e01829a807a13a3f9d50226f"
libc = "musl"
os = "linux"

    [[DecFP.download]]
    sha256 = "80b8f678fab92d4a00d99d4fe32fe1ee8f63764234283686ccde07bd80c2afe8"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.3+0/DecFP.v2.0.3.aarch64-linux-musl.tar.gz"
[[DecFP]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d8ef921349e87717ea630c242e2523119ce61f44"
libc = "glibc"
os = "linux"

    [[DecFP.download]]
    sha256 = "d9a0d43f2400c671ad1698ce45b0e0fda6901bfbbef2f585e2806dbdda9118a9"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.3+0/DecFP.v2.0.3.armv6l-linux-gnueabihf.tar.gz"
[[DecFP]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ff8de688dbdc954b499fddc2dc52395cd615a10c"
libc = "musl"
os = "linux"

    [[DecFP.download]]
    sha256 = "eb2b49cf282ae59b166d804030e475ebe37d22232531bb959322a1bc4b4294dd"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.3+0/DecFP.v2.0.3.armv6l-linux-musleabihf.tar.gz"
[[DecFP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8243f3ffd9f0a129963c59a12a47333b22edebfc"
libc = "glibc"
os = "linux"

    [[DecFP.download]]
    sha256 = "30ae6a0e6dd29a9f145de922296ff9de8de9334d9b6cc2221cbc84b4a668fb5d"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.3+0/DecFP.v2.0.3.armv7l-linux-gnueabihf.tar.gz"
[[DecFP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "beda9a2672def9a82842ee35fa15cc4fb6b52fe4"
libc = "musl"
os = "linux"

    [[DecFP.download]]
    sha256 = "8487c892d877373d565d39f26881b492accd3af03d6a8485bdacb8cfa916d0b6"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.3+0/DecFP.v2.0.3.armv7l-linux-musleabihf.tar.gz"
[[DecFP]]
arch = "i686"
git-tree-sha1 = "2f1a326980200b143068522db21146532204f215"
libc = "glibc"
os = "linux"

    [[DecFP.download]]
    sha256 = "8e0f9bd60366d838bcf25ae0d2145dd6a4a73d057d3bc9da2bea7b4e38465486"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.3+0/DecFP.v2.0.3.i686-linux-gnu.tar.gz"
[[DecFP]]
arch = "i686"
git-tree-sha1 = "0c6099112d57a7a2882851a426cf469d8976887d"
libc = "musl"
os = "linux"

    [[DecFP.download]]
    sha256 = "b241923d001f17f9a727edbffb61d1ac30e302ec7785cd6b328b080a0ebdf5c9"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.3+0/DecFP.v2.0.3.i686-linux-musl.tar.gz"
[[DecFP]]
arch = "i686"
git-tree-sha1 = "e83256ad6243ff3aee51dde24b49a1e6a969afd8"
os = "windows"

    [[DecFP.download]]
    sha256 = "d28aa2b7389224a1325838273dd9baf501fb02078ab7de7cb2d762278affe8ac"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.3+0/DecFP.v2.0.3.i686-w64-mingw32.tar.gz"
[[DecFP]]
arch = "powerpc64le"
git-tree-sha1 = "ea8ddcfbc5a7b13236b8afd4f51e52f424977373"
libc = "glibc"
os = "linux"

    [[DecFP.download]]
    sha256 = "f7b7af16a9eb95c350de17e32d2cfee92520cbb1c97b14c82cedc813148209af"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.3+0/DecFP.v2.0.3.powerpc64le-linux-gnu.tar.gz"
[[DecFP]]
arch = "x86_64"
git-tree-sha1 = "f50913b35554fe737af37f7d601fee4692d6afa4"
os = "macos"

    [[DecFP.download]]
    sha256 = "1eea8f3690c46403bc1179e11c31d1ee01155256a754ec9d7d729ffcc3344dd9"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.3+0/DecFP.v2.0.3.x86_64-apple-darwin.tar.gz"
[[DecFP]]
arch = "x86_64"
git-tree-sha1 = "3811e5cc5635909f8e0fd099d779d0f1b7a9a36d"
libc = "glibc"
os = "linux"

    [[DecFP.download]]
    sha256 = "711b5bf28f78a884d871cc4bf54e4257bb6ea81a134638f85ed27d68bc2935eb"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.3+0/DecFP.v2.0.3.x86_64-linux-gnu.tar.gz"
[[DecFP]]
arch = "x86_64"
git-tree-sha1 = "4647c828671d54d2c093b8d81e01e735bd8725b7"
libc = "musl"
os = "linux"

    [[DecFP.download]]
    sha256 = "214de4fcc13595c33ab3ec78c0fc3370b5311d113fe03143e71395f97ea83dcb"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.3+0/DecFP.v2.0.3.x86_64-linux-musl.tar.gz"
[[DecFP]]
arch = "x86_64"
git-tree-sha1 = "18fd1f3b25b90959c7a7bbcdaed5e322adf510d7"
os = "freebsd"

    [[DecFP.download]]
    sha256 = "b8fbc7cb3cb06d9fa2105c0ce6b1d3dc75a4c64f94c6d7757291b2278f404696"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.3+0/DecFP.v2.0.3.x86_64-unknown-freebsd.tar.gz"
[[DecFP]]
arch = "x86_64"
git-tree-sha1 = "5538367f0cd8effe18199ce930c2fd0f35592309"
os = "windows"

    [[DecFP.download]]
    sha256 = "06e48d5d71cafe6b1880e26970ff2f036fe567177400ad91484d31c1abdf8457"
    url = "https://github.com/JuliaBinaryWrappers/DecFP_jll.jl/releases/download/DecFP-v2.0.3+0/DecFP.v2.0.3.x86_64-w64-mingw32.tar.gz"
